#!/bin/bash

# Builder.io Quick Connect Script
echo "🚀 Builder.io Visual Editor Setup"
echo "================================"
echo ""
echo "Your API Key is configured: e19bb9554845477c84fa4345b2f84479"
echo ""
echo "Follow these steps:"
echo ""
echo "1. Open Builder.io Dashboard:"
echo "   https://builder.io/content"
echo ""
echo "2. Create a New Entry:"
echo "   - Click 'New Entry'"
echo "   - Choose 'Page' model"
echo "   - Name it 'Portfolio Home'"
echo ""
echo "3. Start Visual Editing:"
echo "   - Drag and drop components"
echo "   - Change colors with color picker"
echo "   - Resize elements visually"
echo ""
echo "4. Preview URL:"
echo "   Set preview URL to: file://$PWD/index.html"
echo ""
echo "5. Export Changes:"
echo "   - Click 'Publish'"
echo "   - Copy the generated code"
echo "   - I'll help integrate it!"
echo ""
echo "Quick Links:"
echo "- Visual Editor: https://builder.io/editor"
echo "- Your Content: https://builder.io/content"
echo "- API Explorer: https://builder.io/api-explorer"